# Generated by Django 6.0.1 on 2026-01-08 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issue_type', models.CharField(choices=[('SOFTWARE', 'Software Issue'), ('HARDWARE', 'Hardware Issue'), ('NETWORK', 'Network Issue'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('status', models.CharField(choices=[('NEW', 'Pending Admin Acceptance'), ('REJECTED', 'Rejected by Admin'), ('IN_PROGRESS', 'Admin In Progress'), ('ADMIN_CLOSED', 'Closed by Admin'), ('FINAL_CLOSED', 'Final Closed')], default='NEW', max_length=20)),
                ('approval_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING_HOD', 'Pending HOD Approval'), ('PENDING_MANAGER', 'Pending Manager Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=30)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_closed_at', models.DateTimeField(blank=True, null=True)),
                ('final_closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_raised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
        ),
    ]
