# Generated by Django 6.0.1 on 2026-01-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickethistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketHistory',
        ),
    ]
